version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - run: go get -u github.com/mitchellh/gox
      - checkout
      - run:
          name: cross compile
          command: |
            CGO_ENABLED=0 gox -os="linux darwin windows" -arch="amd64" -ldflags="-s -w" -output="./dist/grpc-client-cli_{{.OS}}_{{.Arch}}" ./cmd/grpc-client-cli
      - run: go get github.com/jstemmer/go-junit-report
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: run tests
          command: |
            go test -v ./... | tee ${TEST_RESULTS}/testresults.txt
            cat ${TEST_RESULTS}/testresults.txt | go-junit-report > ${TEST_RESULTS}/testresults.xml
      - store_test_results:
          path: /tmp/test-results
      - persist_to_workspace:
          root: .
          paths:
            - ./dist
  publish-github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/dist/
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-.*)?$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-.*)?$/
